"""Render a teka's ``scripts/mail/.env`` for imap-extract.

cmirror is machine-wide; imap-extract is per-directory *on purpose* — different
tekas may use different IMAP accounts/servers. So secrets are NOT centralised.
This shim composes a per-teka ``.env`` from an optional shared-secrets file (a
sensible default account) plus the one value that actually varies per teka: the
IMAP folder/label. The rendered ``.env`` only ever exists locally (cmirror then
encrypts it like any other teka file). Tekas are not git repos — local-only,
encrypted-backed-up — so there is no .gitignore to lean on; treat .env as the
secret it is and never share it.

Config (``.env``) and sync state (``state.json``, written to cwd at run time)
live in ``scripts/mail/`` — deliberately *outside* ``intake/``. ``intake/mail/``
is the transient drain (``TARGET_DIR``) that gets emptied on filing and can be
wiped and recreated without losing config or the imap-extract watermark.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

DEFAULT_SHARED = Path("~/.config/lifeproj/imap-shared.env").expanduser()

_PLACEHOLDER = """\
# Fill these in (or point --imap-shared at a file that already has them).
IMAP_HOST=imap.example.com
IMAP_PORT=993
IMAP_SECURE=true
IMAP_USER=you@example.com
IMAP_PASSWORD=CHANGE_ME_app_password
"""


def render(imap_folder: str, target_dir: str,
           shared: Optional[Path] = None) -> str:
    """Return the contents of a teka's scripts/mail/.env."""
    shared = shared if shared is not None else DEFAULT_SHARED
    if shared.exists():
        base = shared.read_text().rstrip() + "\n"
        origin = f"# Account inherited from {shared}\n"
    else:
        base = _PLACEHOLDER
        origin = "# No shared-secrets file found; placeholders written.\n"
    return (
        "# Generated by lifeproj for imap-extract. Local secret — do not share.\n"
        f"{origin}{base}"
        f"IMAP_FOLDER={imap_folder}\n"
        f"TARGET_DIR={target_dir}\n"
    )


def write(teka_dir: Path, imap_folder: str,
          shared: Optional[Path] = None) -> Path:
    # Persistent: .env lives here, and imap-extract writes state.json to cwd when
    # run from here. Kept out of intake/ so the drain stays disposable.
    config_dir = teka_dir / "scripts" / "mail"
    # Transient drain (TARGET_DIR): imap-extract drops one .md per email here.
    drain_dir = teka_dir / "intake" / "mail"
    config_dir.mkdir(parents=True, exist_ok=True)
    drain_dir.mkdir(parents=True, exist_ok=True)
    env_path = config_dir / ".env"
    # TARGET_DIR is read from scripts/mail/ but points at the drain — write it
    # absolute so it resolves correctly no matter where imap-extract is run from.
    env_path.write_text(render(imap_folder, str(drain_dir.resolve()), shared))
    return env_path
