"""Render a teka's ``intake/mail/.env`` for imap-extract.

cmirror is machine-wide; imap-extract is per-directory *on purpose* — different
tekas may use different IMAP accounts/servers. So secrets are NOT centralised.
This shim composes a per-teka ``.env`` from an optional shared-secrets file (a
sensible default account) plus the one value that actually varies per teka: the
IMAP folder/label. The rendered ``.env`` is gitignored and only ever exists
locally (cmirror then encrypts it like any other teka file).
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

DEFAULT_SHARED = Path("~/.config/lifeproj/imap-shared.env").expanduser()

_PLACEHOLDER = """\
# Fill these in (or point --imap-shared at a file that already has them).
IMAP_HOST=imap.example.com
IMAP_PORT=993
IMAP_SECURE=true
IMAP_USER=you@example.com
IMAP_PASSWORD=CHANGE_ME_app_password
"""


def render(imap_folder: str, target_dir: str,
           shared: Optional[Path] = None) -> str:
    """Return the contents of a teka's intake/mail/.env."""
    shared = shared if shared is not None else DEFAULT_SHARED
    if shared.exists():
        base = shared.read_text().rstrip() + "\n"
        origin = f"# Account inherited from {shared}\n"
    else:
        base = _PLACEHOLDER
        origin = "# No shared-secrets file found; placeholders written.\n"
    return (
        "# Generated by lifeproj for imap-extract. Gitignored; do not commit.\n"
        f"{origin}{base}"
        f"IMAP_FOLDER={imap_folder}\n"
        f"TARGET_DIR={target_dir}\n"
    )


def write(teka_dir: Path, imap_folder: str,
          shared: Optional[Path] = None) -> Path:
    mail = teka_dir / "intake" / "mail"
    mail.mkdir(parents=True, exist_ok=True)
    target = mail  # imap-extract drops .md here; state.json lands in cwd at run time
    env_path = mail / ".env"
    env_path.write_text(render(imap_folder, str(target), shared))
    return env_path
